### ISSUE TITLE
BLE Bug Fixes

### ISSUE THREAD

**Issue by AlyKamel** [deokgyuhan/flutter_ble_peripheral_central#3]
Hello, thank you for this package! It helped me a lot in my project.

Before I got this package to work, I had to fix a number of bugs. I would like to publish those fixes to help anyone using this package. My fixes were tested only on my devices, so I can't guarantee they will work for all different devices, but they should at least be a good starting point.

I can open a PR for each bug I fix in this package, but some of the bugs are in BLEProof-collection. I could submit my fixes there and you pull them into this repo. What do you think?

**Comment by deokgyuhan** [comment]
> Hello, thank you for this package! It helped me a lot in my project.
> 
> Before I got this package to work, I had to fix a number of bugs. I would like to publish those fixes to help anyone using this package. My fixes were tested only on my devices, so I can't guarantee they will work for all different devices, but they should at least be a good starting point.
> 
> I can open a PR for each bug I fix in this package, but some of the bugs are in BLEProof-collection. I could submit my fixes there and you pull them into this repo. What do you think?

Hi AlyKamel. thank you for showing interest in the plugin. It would be great if you could send a pull request. Thank you.

**Comment by AlyKamel** [comment]
Hello deokgyuhan, I have opened a bunch of pull requests. Most of them can be merged directly, some require some testing. Thank you!
